export const facilities = [
  {
    id: 1,
    icon: "local_hospital",
    title: "Hospitals",
    description: "24/7 emergency care and specialist clinics.",
    iconBoxClass: "bg-primary-fixed text-primary group-hover:bg-primary",
  },
  {
    id: 2,
    icon: "restaurant",
    title: "Restaurants",
    description: "Authentic Rajasthani and global cuisines.",
    iconBoxClass: "bg-secondary-fixed text-secondary group-hover:bg-secondary",
  },
  {
    id: 3,
    icon: "coffee",
    title: "Cafes",
    description: "Best hangout spots and artisan coffee.",
    iconBoxClass: "bg-tertiary-fixed text-tertiary group-hover:bg-tertiary",
  },
  {
    id: 4,
    icon: "school",
    title: "Schools",
    description: "Top rated educational institutions.",
    iconBoxClass: "bg-primary-fixed text-primary group-hover:bg-primary",
  },
  {
    id: 5,
    icon: "hotel",
    title: "Hotels",
    description: "Luxury stay and budget accommodations.",
    iconBoxClass: "bg-secondary-fixed text-secondary group-hover:bg-secondary",
  },
  {
    id: 6,
    icon: "shopping_bag",
    title: "Shops",
    description: "Traditional markets and modern malls.",
    iconBoxClass: "bg-tertiary-fixed text-tertiary group-hover:bg-tertiary",
  },
  {
    id: 7,
    icon: "park",
    title: "Parks",
    description: "Green spaces for relaxation and play.",
    iconBoxClass: "bg-primary-fixed text-primary group-hover:bg-primary",
  },
  {
    id: 8,
    icon: "fitness_center",
    title: "Gyms",
    description: "Fitness centers and wellness studios.",
    iconBoxClass: "bg-secondary-fixed text-secondary group-hover:bg-secondary",
  },
  {
    id: 9,
    icon: "account_balance",
    title: "Banks",
    description: "Secure banking and ATM services.",
    iconBoxClass: "bg-tertiary-fixed text-tertiary group-hover:bg-tertiary",
  },
  {
    id: 10,
    icon: "castle",
    title: "Tourist Places",
    description: "Historical sites, temples, and havelis.",
    iconBoxClass: "bg-primary-fixed text-primary group-hover:bg-primary",
  },
];
