export const navigationData = [
  { id: 1, name: "Home", path: "/" },
  { id: 2, name: "Directory", path: "#" },
  { id: 3, name: "Help", path: "/servicedetails" },
];

export const directoryCategories = [
  {
    id: 1,
    name: "Hospitals",
    path: "/hospitals",
    icon: "medical_services",
    color: "text-red-500",
    bg: "bg-red-50",
  },
  {
    id: 2,
    name: "Restaurants",
    path: "/restaurants",
    icon: "restaurant",
    color: "text-orange-500",
    bg: "bg-orange-50",
  },
  {
    id: 3,
    name: "Cafes",
    path: "/cafes",
    icon: "local_cafe",
    color: "text-brown-500",
    bg: "bg-orange-100/30",
  },
  {
    id: 4,
    name: "Schools",
    path: "/schools",
    icon: "school",
    color: "text-blue-500",
    bg: "bg-blue-50",
  },
  {
    id: 5,
    name: "Hotels",
    path: "/hotels",
    icon: "hotel",
    color: "text-indigo-500",
    bg: "bg-indigo-50",
  },
  {
    id: 6,
    name: "Shops",
    path: "/shops",
    icon: "shopping_bag",
    color: "text-pink-500",
    bg: "bg-pink-50",
  },
  {
    id: 7,
    name: "Parks",
    path: "/parks",
    icon: "park",
    color: "text-green-500",
    bg: "bg-green-50",
  },
  {
    id: 8,
    name: "Gyms",
    path: "/gyms",
    icon: "fitness_center",
    color: "text-slate-700",
    bg: "bg-slate-100",
  },
  {
    id: 9,
    name: "Banks",
    path: "/banks",
    icon: "account_balance",
    color: "text-emerald-600",
    bg: "bg-emerald-50",
  },
  {
    id: 10,
    name: "Tourist Places",
    path: "/tourist-places",
    icon: "map",
    color: "text-amber-600",
    bg: "bg-amber-50",
  },
];
